[package]
name = "dink"
version = "0.8.0"
edition = "2021"

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy_ecs_tilemap = "0.4.0"
env_logger = "0.9.0"
log = "0.4.14"
noise = "0.7.0"
rand = "0.8.4"
